package com.google.android.gms.internal;

import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.PendingResult$zza;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import java.util.concurrent.TimeUnit;

public final class zzln<R extends Result> extends OptionalPendingResult<R> {
    private final zzlc<R> zzacI;

    public zzln(PendingResult<R> pendingResult) {
        if (!(pendingResult instanceof zzlc)) {
            throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
        }
        this.zzacI = (zzlc) pendingResult;
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public R await() {
        return (R) this.zzacI.await();
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public R await(long j, TimeUnit timeUnit) {
        return (R) this.zzacI.await(j, timeUnit);
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public void cancel() {
        this.zzacI.cancel();
    }

    @Override // com.google.android.gms.common.api.OptionalPendingResult
    public R get() {
        if (isDone()) {
            return (R) await(0L, TimeUnit.MILLISECONDS);
        }
        throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public boolean isCanceled() {
        return this.zzacI.isCanceled();
    }

    @Override // com.google.android.gms.common.api.OptionalPendingResult
    public boolean isDone() {
        return this.zzacI.isReady();
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public void setResultCallback(ResultCallback<? super R> resultCallback) {
        this.zzacI.setResultCallback(resultCallback);
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public void setResultCallback(ResultCallback<? super R> resultCallback, long j, TimeUnit timeUnit) {
        this.zzacI.setResultCallback(resultCallback, j, timeUnit);
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public void zza(PendingResult$zza pendingResult$zza) {
        this.zzacI.zza(pendingResult$zza);
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public Integer zznF() {
        return this.zzacI.zznF();
    }
}
