package com.sonyericsson.android.camera.research;

/* JADX INFO: loaded from: classes.dex */
public enum LocalResearchUtil$MeasurementKey {
    LAUNCH_COLD_BOOT_FROM_HOME_READY_FOR_USE,
    LAUNCH_COLD_BOOT_FROM_LOCKSCREEN_READY_FOR_USE,
    LAUNCH_COLD_BOOT_FROM_CAMERAKEY_READY_FOR_USE,
    LAUNCH_COLD_BOOT_FROM_LIFTTRIGGER_READY_FOR_USE,
    LAUNCH_WARM_BOOT_FROM_HOME_READY_FOR_USE,
    LAUNCH_WARM_BOOT_FROM_LOCKSCREEN_READY_FOR_USE,
    LAUNCH_WARM_BOOT_FROM_CAMERAKEY_READY_FOR_USE,
    LAUNCH_WARM_BOOT_FROM_LIFTTRIGGER_READY_FOR_USE,
    VIDEO_RECORDING_STOP_READY_FOR_USE,
    CLOSE_INITIAL_RESPONSE,
    CLOSE_READY_FOR_USE,
    SHOT_TO_SHOT_DELAY
}
