package com.sonymobile.cameracommon.research.parameters;

/* JADX INFO: loaded from: classes.dex */
public enum Event$WizardPage implements Event$Action {
    LOCATION_WIZARD,
    PREDICTIVE_LAUNCH_WIZARD,
    SIDE_SENSING_WIZARD,
    EYE_POSITION_WIZARD,
    HAND_SHUTTER_WIZARD,
    SUPER_SLOWMOTION_WIZARD1,
    SUPER_SLOWMOTION_WIZARD2,
    SUPER_SLOWMOTION_WIZARD3,
    SUPER_SLOWMOTION_WIZARD4,
    ONE_SHOT_WIZARD,
    SLOWMOTION_WIZARD1,
    SLOWMOTION_WIZARD2,
    READMORE_SUPER_SLOWMOTION_WIZARD1,
    READMORE_SUPER_SLOWMOTION_WIZARD2,
    READMORE_SUPER_SLOWMOTION_WIZARD3,
    READMORE_ONE_SHOT_WIZARD,
    READMORE_SLOWMOTION_WIZARD1,
    READMORE_SLOWMOTION_WIZARD2,
    SUPERIOR_AUTO_FUSION_WIZARD,
    VIDEO_FUSION_WIZARD1,
    VIDEO_FUSION_WIZARD2,
    MANUAL_FUSION_WIZARD1,
    MANUAL_FUSION_WIZARD2,
    UNKNOWN
}
