package com.sonyericsson.android.camera.view.baselayout.onscreenbutton;

import com.sonyericsson.android.camera.view.UserEventHandler$TouchEventSource;

public enum OnScreenButtonItemFactory$ButtonType implements UserEventHandler$TouchEventSource {
    CAPTURE_LARGE,
    CAPTURE_SMALL,
    CAPTURE_WITH_SELFTIMER_LARGE,
    CAPTURE_WITH_SELFTIMER_LONG,
    CAPTURE_WITH_SELFTIMER_SHORT,
    CANCEL_SELFTIMER_LARGE,
    CANCEL_SELFTIMER_SIDE,
    START_RECORDING_LARGE,
    STOP_RECORDING_IN_PAUSE_LARGE,
    STOP_RECORDING_LARGE,
    STOP_RECORDING_SMALL,
    RESUME_RECORDING_SMALL,
    PAUSE_RECORDING_SMALL,
    TRIGGER_SUPER_SLOW_MOTION,
    TRIGGER_SUPER_SLOW_MOTION_PRESSED,
    TRIGGER_SUPER_SLOW_MOTION_DISABLED,
    TOUCH_CAPTURE,
    TOUCH_CAPTURE_WITH_SELFTIMER,
    TOUCH_CAPTURE_WITH_SELFTIMER_LONG,
    TOUCH_CAPTURE_WITH_SELFTIMER_SHORT,
    TOUCH_RECORDING_START,
    SIDE_TOUCH_STOP_RECORDING,
    SIDE_TOUCH_PAUSE_RECORDING,
    SIDE_TOUCH_START_RECORDING,
    SIDE_TOUCH_SNAPSHOT_RECORDING,
    SIDE_TOUCH_STOP_RECORDING_IN_PAUSE,
    SIDE_TOUCH_RESUME_RECORDING
}
