package com.sonyericsson.android.camera.controller;

/* JADX INFO: loaded from: classes.dex */
public enum StateMachine$StaticEvent {
    EVENT_ON_PHOTO_STACK_INITIALIZED,
    EVENT_ON_HEAD_UP_DISPLAY_INITIALIZED,
    EVENT_ON_SCENE_MODE_CHANGED,
    EVENT_ON_FACE_DETECTED,
    EVENT_ON_OBJECT_TRACKED,
    EVENT_ON_ORIENTATION_CHANGED,
    EVENT_ON_LAZY_INITIALIZATION_TASK_RUN,
    EVENT_ON_OBJECT_TRACKING_LOST,
    EVENT_ON_GESTURE_SHUTTER_SETTING_CHANGED,
    EVENT_ON_SD_PERMISSION_DISPLAY_FINISHED,
    EVENT_ON_PREVIEW_STARTED
}
